### PR TITLE
[Polymer] Clean the hint text after destroying SP module.

### PR DESCRIPTION
**Pull request by DonnaWuDongxia**

### CODE REVIEW

**Comment by DonnaWuDongxia** [comment]
@leonhsl please help to review.

**Comment by DonnaWuDongxia** [comment]
@halton the trybot seems sufferring proxy issue.

**Comment by halton** [comment]
@huningxin seems https://closure-linter.googlecode.com/svn/trunk/ is down. When I visit the parent url, it jump to https://github.com/google/closure-linter, I'm going to submit a PR to update the script to see whether it is fixed.

**Comment by leonhsl** [comment]
lgtm

**Comment by leonhsl** [comment]
Merged

**Pull request merged**
