### PR TITLE
[Polymer][Face]Add usage script

### PR DESCRIPTION
**Pull request by leonhsl**

### CODE REVIEW

**Comment by leonhsl** [comment]
@halton  @jondong  @DonnaWuDongxia PTAL, Thanks~

**Comment by halton** [comment]
@leonhsl could you squash your commits into one?

**Comment by leonhsl** [comment]
Done. PTAL, Thanks~

**Comment by leonhsl** [comment]
@DonnaWuDongxia @jondong  We'd better put all our usage scripts into `manuals` folder just like this PR. Thanks~

**Comment by halton** [comment]
Great script, it is very helpful for users who first time play it. I am going to merge it.

**Pull request merged**
