### PR TITLE
[Sample] trigger the user permission prompt by getUserMedia

### PR DESCRIPTION
**Pull request by huningxin**
BUG=XWALK-6551

### CODE REVIEW

**Comment by huningxin** [comment]
When using Crosswalk Crosswalk-19.48.498.0 (https://download.01.org/crosswalk/releases/crosswalk/windows/canary/19.48.498.0/)

Trunk code:
image

With this PR:

Permission prompt:
image

After user clicks "Allow":
image

**Comment by huningxin** [comment]
@jondong @leonhsl , PTAL. Thanks!

**Comment by leonhsl** [comment]
LGTM and Thanks!

**Comment by jondong** [comment]
LGTM, thanks for the PR. Merging

**Pull request merged**
