### PR TITLE
Move sample GN logic into sample/BUILD.gn

### PR DESCRIPTION
**Pull request by halton**
To avoid the build supportting files (BUILD.gn, package_sample.py) get
packaged, the sample assets into sample/src.

### CODE REVIEW

**Comment by halton** [comment]
@DonnaWuDongxia  please review this PR.

**Comment by halton** [comment]
The trybot failure are about JS style errors on `three.js`, I'm working on ignore features on the lint.py.

**Comment by halton** [comment]
The ignore feature is ready locally, just wait for https://github.com/crosswalk-project/crosswalk-extensions-sdk/pull/35 to merge.

**Comment by huningxin** [comment]
I suggest we put the third party code in a `third_party` directory and let linter ingore that.

**Comment by halton** [comment]
I've implemented locally with the feature can ignore files specified in .lintignore, will upload PR after the style PR merged.

**Comment by halton** [comment]
https://github.com/crosswalk-project/crosswalk-extensions-sdk/pull/36 is upload with lint ignore feature.

**Comment by halton** [comment]
Finally the trybot green. @DonnaWuDongxia please review.

**Pull request merged**
