### PR TITLE
[Test] Integrate W3C testharness.js test framework for API testing

### PR DESCRIPTION
**Pull request by zqzhang**
without any modification from
https://github.com/w3c/testharness.js/commit/eaa4c5f793f07e2dc6edbeddb3d5bb6275ebd580

### CODE REVIEW

**Comment by zqzhang** [comment]
Most of Crosswalk test suites for API testing are using this test framework, and I would like to use it too here.

The CI failure (JavaScript lint) is somehow expected because https://github.com/w3c/testharness.js/blob/master/testharness.js#L2671 only specifies that "vim: set expandtab shiftwidth=4 tabstop=4:".

@huningxin please take a look, thanks.

**Comment by huningxin** [comment]
@zqzhang , thanks for this PR!

I am wondering how you guys maintain this test framework in Crosswalk test suites? Do you have a central repo to host all Crosswalk test suites? Will RealSense API test be part of that?

**Comment by zqzhang** [comment]
> Do you have a central repo to host all Crosswalk test suites?

Yes, in https://github.com/crosswalk-project/crosswalk-test-suite.

In that repository, this test framework is integrated at

https://github.com/crosswalk-project/crosswalk-test-suite/tree/master/tools/resources/testharness

... and is built into each test suite by packaging tool.

>  Will RealSense API test be part of that?

Yes, it can be part of that repository, I think, since you just implemented an app-tools hook to build sample application.

Then I will create a test suite named `webapi-realsense-xwalk-tests` at https://github.com/crosswalk-project/crosswalk-test-suite/tree/master/webapi for all the APIs implemented in this repository. Is that OK to you?

**Comment by zqzhang** [comment]
After offline talk to @chunywang, we will create 3 test suites in crosswalk-test-suite repository:
- webapi-dep-xwalk-tests
- webapi-face-xwalk-tests
- webapi-sp-xwalk-tests

So close this pull request.

**Comment by huningxin** [comment]
The plan sounds good to me. Thanks!

**Pull request closed without merging**
