### PR TITLE
[Hooks] change the sample installer with RS runtime to MSI format

### PR DESCRIPTION
**Pull request by DonnaWuDongxia**
BUG=XWALK-6448

### CODE REVIEW

**Comment by DonnaWuDongxia** [comment]
@huningxin Please help to review.

**Comment by huningxin** [comment]
@DonnaWuDongxia , thanks for this PR!

I downloaded the sample_installers.zip from https://ci.appveyor.com/project/recbuilder/realsense-extensions-crosswalk-a87d8/build/19.6.0.109/artifacts, but it doesn't contains the installer with runtime. Did I miss anything?

**Comment by DonnaWuDongxia** [comment]
@huningxin  Oh, we need to update the App-tools to include this PR: https://github.com/crosswalk-project/crosswalk-app-tools/pull/118

Because we used the kept .wxs file in the temp folder.
Buildbot failed to package the installer, see following site:
https://ci.appveyor.com/project/recbuilder/realsense-extensions-crosswalk-a87d8/build/19.6.0.109

**Comment by huningxin** [comment]
@DonnaWuDongxia , thanks for investigation. Can you get it updated in this PR? You may need to refer to https://github.com/crosswalk-project/realsense-extensions-crosswalk/pull/28/commits/5825786da8aaec983c521484eca32be1906805ea, to change back to master install.

**Comment by DonnaWuDongxia** [comment]
@huningxin Please help to check again.

**Comment by huningxin** [comment]
Verified. Works great! Thanks!

LGTM and Merging.

@leonhsl , you may need to check whether the binary sign still works with msi installer. Thanks!

**Comment by leonhsl** [comment]
I verified that now we only need to sign the MSI installers directly. 
Also updated wiki page https://github.com/otcshare/realsense-extensions-crosswalk/wiki/Sign-binaries

**Comment by huningxin** [comment]
Great! Thanks @leonhsl !

**Pull request merged**
