### PR TITLE
[Face] Start preview and FaceModule after clicking 'start' button.

### PR DESCRIPTION
**Pull request by leonhsl**
BUG=XWALK-6506

### CODE REVIEW

**Comment by leonhsl** [comment]
@huningxin @halton PTAL, Thanks~

**Comment by huningxin** [comment]
LGTM. Thanks for the PR!

**Comment by leonhsl** [comment]
Updated this PR again just for code convention: %s/processed_sample/processedSample/g

**Comment by huningxin** [comment]
Great! Merging.

**Pull request merged**
