### PR TITLE
[Face] Add FaceModule APIs to support alert handling.

### PR DESCRIPTION
**Pull request by leonhsl**
RSSDK C++ interface FaceConfiguration apis:
DisableAlert
DisableAllAlerts
EnableAlert
EnableAllAlerts
IsAlertEnabled
SubscribeAlert
UnsubscribeAlert

RSSDK C++ alert data struct: PXCFaceData::AlertData
alert type: PXCFaceData::AlertData::AlertType

BUG=XWALK-6449

### CODE REVIEW

**Comment by leonhsl** [comment]
@huningxin This initial PR only updated face.html spec, would you PTAL firstly, if it's OK I'll proceed implementing, Thanks~

**Comment by huningxin** [comment]
@leonhsl , the API looks good to me. Thanks!

**Comment by leonhsl** [comment]
@huningxin Would you PTAL? Thanks~
- Impl done.
- Sample screen layout is still based on current style, will switch to touch friendly UX together later.
- Only 2 types of alert are supported by RSSDK now, other 4 types of alert will never be triggered.  (RSSDK native sample tells the same thing)
  PXCFaceData::AlertData::AlertType::ALERT_NEW_FACE_DETECTED
  PXCFaceData::AlertData::AlertType::ALERT_FACE_LOST

**Comment by huningxin** [comment]
LGTM. Thanks for the PR. Merging.

**Pull request merged**
