### PR TITLE
[Sample] Install crosswalk-app-tool is not available.

### PR DESCRIPTION
**Pull request by halton**
Formatting this file to unix line ending as well.

BUG=https://crosswalk-project.org/jira/browse/XWALK-6821

### CODE REVIEW

**Comment by halton** [comment]
@huningxin PTAL

**Comment by huningxin** [comment]
There is a lint issue. Please take a look. Thanks.

**Comment by halton** [comment]
> There is a lint issue. Please take a look. Thanks.

Yes, I'm working on it.

**Comment by halton** [comment]
@huningxin trybot green.

**Comment by huningxin** [comment]
LGTM and merging.

**Pull request merged**
