### PR TITLE
[SP] Code refactory and new UI for scene perception sample

### PR DESCRIPTION
**Pull request by DonnaWuDongxia**
It's a big patch. But I'd like to keep the new UI in code base, for two reasons:
1. Adam can access the the new UI for the touchable UX design
2. The new UI is some kind touchable and scalable, we can keep a stamp in the code base, in case we need this version of sample in the future.

### CODE REVIEW

**Comment by DonnaWuDongxia** [comment]
@huningxin please help to review. It's a big patch, but most lines are code translation.

**Comment by huningxin** [comment]
I like the new sample much. Thanks for making this, @DonnaWuDongxia !

General questions:
1. do you want to replace the old one with the new one? I think we just need to keep one SP sample. It should be the new one. What do you think?
2. it might be better to make a directory to hold the SP code, as they are several files. Actually, we need to do this for other samples.

**Comment by huningxin** [comment]
I found I cannot change the viewport of volume preview after stop. It doesn't align to the native sample. Is it an issue?

**Comment by huningxin** [comment]
If I didn't view the volume and stop, I cannot see the volume preview by pressing 'm'. Is it an issue?

**Comment by huningxin** [comment]
I cannot scale the meshes. It seems a regression.

**Comment by DonnaWuDongxia** [comment]
@huningxin Thanks for review. I will take the two points.
General questions:

```
do you want to replace the old one with the new one? I think we just need to keep one SP sample. It should be the new one. What do you think?
it might be better to make a directory to hold the SP code, as they are several files. Actually, we need to do this for other samples.
```

**Comment by DonnaWuDongxia** [comment]
@huningxin please help to review.  Updated according to previous comments.

**Comment by DonnaWuDongxia** [comment]
This PR depend on: https://github.com/crosswalk-project/realsense-extensions-crosswalk/pull/38

**Comment by huningxin** [comment]
@DonnaWuDongxia , thanks for the update!

> I found I cannot change the viewport of volume preview after stop. It doesn't align to the native sample. Is it an issue?

It works for the first time I changed to volume preview. After I switched back and forth several times after stop, the sample reports "Status: Failed to queryVolumePreview". Please take a look.

**Comment by DonnaWuDongxia** [comment]
@huningxin The code get the delta ration angle from mouse click event to change the render matrix. It turns out that the render matrix we got from the algrithm can't got volume preview from SP module. I have tried the value in native, it can't get the volume image neither. Currently, I have no idea to solve this problem properly. Any suggestions?

**Comment by huningxin** [comment]
Synced with @DonnaWuDongxia and @zqzhang . 

There will be error message to show "can't to get volume preview data". And user is able to click "c" to reset the viewpoint. We can improve the user experience with following PR.

LGTM! and merge. Thanks much for this great improvement, @DonnaWuDongxia !

**Pull request merged**
