### PR TITLE
[SP] Use glMatrix in SP sample instead of THREE.js.

### PR DESCRIPTION
**Pull request by DonnaWuDongxia**
The sample can leverage SIMD feature in Crosswalk by using glMatrix.

### CODE REVIEW

**Comment by DonnaWuDongxia** [comment]
@huningxin @leonhsl please help to reivew.

**Comment by DonnaWuDongxia** [comment]
updated, @leonhsl @huningxin please help to review. Thanks!

**Comment by leonhsl** [comment]
lgtm and merging

**Comment by leonhsl** [comment]
Merged

**Pull request merged**
