### PR TITLE
[Sample] Initial impl for index.html

### PR DESCRIPTION
**Pull request by leonhsl**
BUG=XWALK-6582

### CODE REVIEW

**Comment by leonhsl** [comment]
@huningxin @DonnaWuDongxia @jondong PTAL, Thanks~

**Comment by huningxin** [comment]
Thanks for making this PR, @leonhsl !

You may need to create a manifest.json so I can use crosswalk to launch it.

**Comment by leonhsl** [comment]
manifest.json done. Thanks~ @huningxin

**Comment by huningxin** [comment]
@leonhsl , thanks for the update! I can launch it with Crosswalk which is cool.

One issue I found that if I click the left area of the drawer button, the drawer will be shown and hidden very quickly. Is it a known issue?

image

**Comment by leonhsl** [comment]
Uploaded again. 
Adjusted the drawer button position according spec and the draw panel's property edgeSwipeSensitivity(How many pixels on the side of the screen are sensitive to edge swipes and peek), the problem disappeared ;-)

**Comment by huningxin** [comment]
It still happens on my desktop.

**Comment by leonhsl** [comment]
Clicking the 'Edge swipe area' will cause "the drawer will be shown and hidden very quickly", it's normal. But clicking on the drawer button should not cause this.
edge_swipe

**Comment by leonhsl** [comment]
@huningxin  Uploaded again. Added a simple shared-styles.html for all pages. PTAL again~

**Comment by huningxin** [comment]
Great. Thanks, @leonhsl !

LGTM. And merging.

**Pull request merged**
