### PR TITLE
[SP][Sample] improve the meshing performance by using raw WebGL

### PR DESCRIPTION
**Pull request by huningxin**
BUG=XWALK-6337

### CODE REVIEW

**Comment by huningxin** [comment]
@DonnaWuDongxia , PTAL. Thanks!

**Comment by huningxin** [comment]
Some data for your reference:
- Trunk code
  Number of vertices: 128195
  Number of faces: 150034
  sceneperception.js:357 mergeMeshes: 400.359ms
  sceneperception.js:484 updateMeshes: 876.641ms
  total: **1277**ms
- PR code
  Number of vertices: 182104
  Number of faces: 207922
  sceneperception.js:525 updateMeshes: 39.624ms
  sceneperception.js:478 mergeMeshes: 13.766ms
  total: **53.39**ms

Given the number of vertices and faces in PR code test is larger than Trunk code test, the speedup is > **23.91X**

**Comment by huningxin** [comment]
There are some TODOs:
1. set frustum by camera intrinsics. It depends on exposing `GetInternalCameraIntrinsics`. 
2. implement light effect with normals.
3. it would be good to allow user to view the meshing in WebGL from different view point. (regression as not using three.js)

I will file issues to track them once this PR merged.

**Comment by huningxin** [comment]
@halton  once asked what's the reasons of not using three.js in this sample. The answers:
1. This sample creates `Geometry` of three.js from SP meshing data. It is related to construct `vertices`, `faces` objects one by one from meshing arrays returned from SP API. When the numbers of faces and faces are large. This process is very time consuming. It is shown in above data.
2. I tried to use `BufferGeometry` of three.js. However, as https://github.com/mrdoob/three.js/issues/8358, the `colors` in Uint8Array is not able to be used. One option is to do normalization in JavaScript code. I didn't try that. And I don't know whether it has more issues ahead.

Longer term, I agree we need to investigate the three.js integration with SP API and fix the issues found, as three.js has lot of useful tools and libraries.

**Comment by DonnaWuDongxia** [comment]
@huningxin,  it's a great step, thank you for all the efforts. I think it also regressed the mouse actions response in the 3D render, right? We haven't use "TrackballControls.js" any more, should we delete it?

**Comment by DonnaWuDongxia** [comment]
Another tick, no camera pose showing any more. I'm trying to integrate this change with my code. Thanks!

**Comment by halton** [comment]
Great improvement, let's go ahead to use raw WebGL now.

**Comment by huningxin** [comment]
> I think it also regressed the mouse actions response in the 3D render, right? 

Yes. I listed it as one TODO.

> We haven't use "TrackballControls.js" any more, should we delete it?

Yes. I will update the PR to remove the link but keep the file in our repo. WDYT?

> Another tick, no camera pose showing any more. I'm trying to integrate this change with my code. Thanks!

Great! Thanks.

**Comment by DonnaWuDongxia** [comment]
line 181:  var meshesCreated = false;
Never used.

**Comment by huningxin** [comment]
> line 181: var meshesCreated = false;

Will remove

**Comment by huningxin** [comment]
> We haven't use "TrackballControls.js" any more, should we delete it?

I am implementing the view point control. I don't want the regression. Will upload soon.

**Comment by huningxin** [comment]
Updated the PR:
1. Addressed the review comments.
2. Reenabled view point control by reusing `TrackballControls` of three.js.

@DonnaWuDongxia , PTAL. Thanks!

**Comment by huningxin** [comment]
> So we can only stop the SP to change the view point, right?

Right. I would like:
1. SP module changes the view point when tracking.
2. Allow users to view the meshing result by mouse only when SP is stopped

**Comment by DonnaWuDongxia** [comment]
LGTM, Thanks!

**Comment by huningxin** [comment]
Thanks much for review! Merging.

**Pull request merged**
